### PR TITLE
Compatibility with react 16

### PR DESCRIPTION
**Pull request by OnlyRefat**
Hi,
Hi on react 16 few things have changed.

PropTypes are now separate package prop-types.
https://facebook.github.io/react/warnings/dont-call-proptypes.html

react-addons-test-utils are deprecated.
https://www.npmjs.com/package/react-addons-test-utils

enzyme has changed because of that.
airbnb/enzyme#976

Thanks for the library. It is coded simply and very powerful 👍

### CODE REVIEW

**Comment by sslotsky** [comment]
Thanks for the PR! My notifications were off for this repo. I'll review ASAP.

**Comment by sslotsky** [comment]
@OnlyRefat can you explain why the enzyme adapter is needed? I thought the newer version of enzyme worked fine with React 16, and I've upgraded a couple projects already without having to do this. 

Another thing I really need to get around to here is to exclude the compiled files from git. They really don't need to be there, but I suppose that's another topic.

Everything looks fine here, just hoping to understand what the adapter business is about. Thanks again for the PR.

**Comment by OnlyRefat** [comment]
@sslotsky thanks for your reply. Airbnb has now adapter system. I have followed their migration guide for react 16.0v . They have a list that with react 16.0v an adapter is needed to make it work. Here is the migration [guide](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#configuring-your-adapter) i have followed.

**Comment by sslotsky** [comment]
@OnlyRefat I realize this PR missed one additional thing: the peer dependencies. They should have been updated to reflect that React 16 is now supported. If you have time to submit that, please do. Otherwise I'll give it a go before I publish.

**Comment by OnlyRefat** [comment]
@sslotsky I will do that and make a PR again today.

**Pull request merged**
